/**
 * Seeder: PublisherSeeder
 * Description: Data lengkap penerbit resmi + 1 entry Indie/Self-Published
 */

const publishersData = [
  // --- 1. Entry Khusus Self-Published / Perorangan ---
  {
    name: 'Self-Published / Indie',
    slug: 'self-published-indie',
    logo: 'publishers/indie.png',
    email: null,
    phone: null,
    website: null,
    address: 'Indonesia',
    description: 'Wadah publikasi buku mandiri bagi penulis independen dan komunitas sastra.',
    is_official: false,
    status: 'active',
  },

  // --- 2. Penerbit Resmi & Major (Data Lama) ---
  {
    name: 'Gramedia Pustaka Utama',
    slug: 'gramedia-pustaka-utama',
    logo: 'publishers/gpu.png',
    email: 'redaksi@gramediapustakautama.id',
    phone: '021-53650110',
    website: 'https://gpu.id',
    address: 'Gedung Kompas Gramedia, Palmerah Barat, Jakarta Pusat',
    description: 'Penerbit mayor terbesar di Indonesia yang menerbitkan ragam fiksi, non-fiksi, dan buku anak.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Mizan Publishing',
    slug: 'mizan-publishing',
    logo: 'publishers/mizan.png',
    email: 'redaksi@mizan.com',
    phone: '022-7834154',
    website: 'https://mizanpublishing.com',
    address: 'Jl. Cinambo No. 135, Cisaranten Wetan, Bandung',
    description: 'Penerbit terkemuka yang berfokus pada buku-buku islami, pemikiran, novel, dan pengayaan diri.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Bentang Pustaka',
    slug: 'bentang-pustaka',
    logo: 'publishers/bentang.png',
    email: 'bentang.pustaka@mizan.com',
    phone: '0274-886637',
    website: 'https://bentangpustaka.com',
    address: 'Jl. Pesona Gading No. 8, Palagan, Yogyakarta',
    description: 'Penerbit fiksi dan populer berkualitas tinggi asal Yogyakarta.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Erlangga',
    slug: 'erlangga',
    logo: 'publishers/erlangga.png',
    email: 'webmaster@erlangga.co.id',
    phone: '021-8717006',
    website: 'https://erlangga.co.id',
    address: 'Jl. H. Baping No. 100, Ciracas, Jakarta Timur',
    description: 'Penerbit spesialis buku teks pelajaran, edukasi, dan literatur pendidikan nasional.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Elex Media Komputindo',
    slug: 'elex-media-komputindo',
    logo: 'publishers/elexmedia.png',
    email: 'elex@gramedia.com',
    phone: '021-53650110',
    website: 'https://elexmedia.id',
    address: 'Gedung Kompas Gramedia, Palmerah Barat, Jakarta Pusat',
    description: 'Penerbit komik, manga, teknologi informasi, bisnis, dan pengembangan diri.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Kepustakaan Populer Gramedia (KPG)',
    slug: 'kpg',
    logo: 'publishers/kpg.png',
    email: 'redaksi@penerbitkpg.id',
    phone: '021-53650110',
    website: 'https://penerbitkpg.id',
    address: 'Gedung Kompas Gramedia Unit 1, Palmerah Barat, Jakarta',
    description: 'Menerbitkan buku sains populer, komik populer, sastra, dan humaniora.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'GagasMedia',
    slug: 'gagasmedia',
    logo: 'publishers/gagasmedia.png',
    email: 'redaksi@gagasmedia.net',
    phone: '021-78883030',
    website: 'https://gagasmedia.net',
    address: 'Jl. H. Montong No. 57, Ciganjur, Jakarta Selatan',
    description: 'Penerbit novel remaja dan romansa populer dengan gaya penulisan kontemporer.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Yoma Publisher / Mojok',
    slug: 'penerbit-mojok',
    logo: 'publishers/mojok.png',
    email: 'redaksi@penerbitmojok.com',
    phone: '0812-2567-8900',
    website: 'https://penerbitmojok.com',
    address: 'Jl. Ambarbinangun No. 31, Kasihan, Bantul, Yogyakarta',
    description: 'Penerbit independen Yogyakarta berfokus pada essai esentrik, novel kritis, dan esai budaya.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Marjin Kiri',
    slug: 'marjin-kiri',
    logo: 'publishers/marjinkiri.png',
    email: 'redaksi@marjinkiri.com',
    phone: '021-78884321',
    website: 'https://marjinkiri.com',
    address: 'Akses UI No. 26, Kelapa Dua, Depok',
    description: 'Penerbit kritis independen untuk wacana ilmu sosial, filsafat, dan sastra berbobot.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Deepublish',
    slug: 'deepublish',
    logo: 'publishers/deepublish.png',
    email: 'cs@deepublish.co.id',
    phone: '0274-4533427',
    website: 'https://penerbitdeepublish.com',
    address: 'Jl. Rajawali Gg. Elang 6 No.3, Sleman, Yogyakarta',
    description: 'Penerbit spesialis buku ajar perkuliahan dan karya ilmiah dosen nasional.',
    is_official: true,
    status: 'active',
  },

  // --- 3. Tambahan 50 Penerbit Baru (Hype, Novel, Populer, Indie, & Akademik) ---
  {
    name: 'Bukune',
    slug: 'bukune',
    logo: 'publishers/bukune.png',
    email: 'redaksi@bukune.com',
    phone: '021-78883030',
    website: 'https://bukune.com',
    address: 'Jl. H. Montong No. 57, Jagakarsa, Jakarta Selatan',
    description: 'Penerbit novel pop, komedi, karya adaptasi Wattpad, dan tren anak muda.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Buku Mojok',
    slug: 'buku-mojok',
    logo: 'publishers/bukumojok.png',
    email: 'redaksi@bukumojok.com',
    phone: '0812-2800-0000',
    website: 'https://bukumojok.com',
    address: 'Kasihan, Bantul, Yogyakarta',
    description: 'Lini khusus menerbitkan novel fiksi satir, esai sosial, dan literatur segar.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Coconut Books',
    slug: 'coconut-books',
    logo: 'publishers/coconutbooks.png',
    email: 'redaksi@coconutbooks.com',
    phone: '021-77889900',
    website: 'https://coconutbooks.id',
    address: 'Depok, Jawa Barat',
    description: 'Penerbit novel best seller adaptasi Wattpad bergenre romansa remaja dan komedi.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Gradien Mediatama',
    slug: 'gradien-mediatama',
    logo: 'publishers/gradien.png',
    email: 'gradienmediatama@gmail.com',
    phone: '0274-488899',
    website: 'https://gradienmediatama.com',
    address: 'Yogyakarta',
    description: 'Penerbit novel fiksi romance, buku puisi viral, dan Self-Improvement kontemporer.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'KTI / Falcon Publishing',
    slug: 'falcon-publishing',
    logo: 'publishers/falcon.png',
    email: 'redaksi@falconpublishing.id',
    phone: '021-7919999',
    website: 'https://falcon.co.id',
    address: 'Duren Tiga, Jakarta Selatan',
    description: 'Penerbit novel populer yang kerap diadaptasi menjadi film bioskop nasional.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Republika Penerbit',
    slug: 'republika-penerbit',
    logo: 'publishers/republika.png',
    email: 'redaksi@bukurepublika.id',
    phone: '021-7819900',
    website: 'https://bukurepublika.id',
    address: 'Jl. Warung Buncit Raya No. 37, Jakarta Selatan',
    description: 'Spesialis fiksi Islami populer, novel sejarah, dan pengayaan pemikiran keislaman.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Noura Books',
    slug: 'noura-books',
    logo: 'publishers/noura.png',
    email: 'redaksi@nourabooks.co.id',
    phone: '021-78880011',
    website: 'https://nourabooks.co.id',
    address: 'Jagakarsa, Jakarta Selatan',
    description: 'Imprint Mizan Group yang fokus pada novel terjemahan internasional dan fiksi fabel.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'DIVA Press',
    slug: 'diva-press',
    logo: 'publishers/divapress.png',
    email: 'redaksidiva@yahoo.com',
    phone: '0274-4332277',
    website: 'https://divapress-online.com',
    address: 'Sampangan, Berbah, Sleman, Yogyakarta',
    description: 'Penerbit raksasa Yogyakarta yang menerbitkan novel sastra, umum, hingga kajian agama.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Inari',
    slug: 'penerbit-inari',
    logo: 'publishers/inari.png',
    email: 'redaksi.inari@gmail.com',
    phone: '021-53650110',
    website: 'https://penerbitinari.com',
    address: 'Jakarta',
    description: 'Lini novel Asian lit (Korea, Jepang) dan fiksi romansa anak muda.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Haru',
    slug: 'penerbit-haru',
    logo: 'publishers/haru.png',
    email: 'kontak@penerbetharu.com',
    phone: '0354-68899',
    website: 'https://penerbetharu.com',
    address: 'Kediri, Jawa Timur',
    description: 'Penerbit novel terjemahan Korea dan Jepang terlengkap yang sangat hype di Indonesia.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Loveable / Fantasious',
    slug: 'loveable',
    logo: 'publishers/loveable.png',
    email: 'loveable.redaksi@gmail.com',
    phone: '021-8770011',
    website: 'https://loveable.co.id',
    address: 'Jakarta Timur',
    description: 'Rumah bagi novel-novel fiksi Wattpad remaja bergenre romantisme, angst, dan fantasi.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Katadepan',
    slug: 'katadepan',
    logo: 'publishers/katadepan.png',
    email: 'redaksi@katadepan.com',
    phone: '021-78883030',
    website: 'https://katadepan.com',
    address: 'Jakarta Selatan',
    description: 'Penerbit fiksi modern yang memfokuskan cerita romansa, kisah inspiratif, dan fiksi urban.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Bune Publisher / Romance',
    slug: 'bune-publisher',
    logo: 'publishers/bune.png',
    email: 'bune.publisher@gmail.com',
    phone: null,
    website: null,
    address: 'Indonesia',
    description: 'Penerbit indie-mayor spesialis cerita fiksi romansa populer.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Baca',
    slug: 'penerbit-baca',
    logo: 'publishers/baca.png',
    email: 'redaksi@penerbitbaca.com',
    phone: '021-78884455',
    website: 'https://penerbitbaca.com',
    address: 'Tangerang Selatan',
    description: 'Menerbitkan karya non-fiksi terjemahan kelas dunia, psikologi, dan pengembangan diri.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Shira Media',
    slug: 'shira-media',
    logo: 'publishers/shiramedia.png',
    email: 'shiramedia@gmail.com',
    phone: '0274-889900',
    website: 'https://shiramedia.com',
    address: 'Sleman, Yogyakarta',
    description: 'Penerbit indie Jogja yang fokus pada buku sastra klasik terjemahan dan pengembangan diri.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Anomali',
    slug: 'penerbit-anomali',
    logo: 'publishers/anomali.png',
    email: 'anomali.penerbit@gmail.com',
    phone: null,
    website: null,
    address: 'Yogyakarta',
    description: 'Penerbit independen yang menyajikan buku sastra eksperimental dan pemikiran kritis.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Buku Fixi Indonesia',
    slug: 'fixi-indonesia',
    logo: 'publishers/fixi.png',
    email: 'info@fixi.com.my',
    phone: null,
    website: 'https://fixi.com.my',
    address: 'Kuala Lumpur / Jakarta',
    description: 'Penerbit novel urban thriller, misteri, dan fiksi gelap bergaya pop.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Kanal Kiri / Kiri Publishing',
    slug: 'kiri-publishing',
    logo: 'publishers/kiri.png',
    email: 'redaksi@penerbitkiri.com',
    phone: null,
    website: null,
    address: 'Bandung, Jawa Barat',
    description: 'Penerbit independen dengan spesialisasi pemikiran kiri, sosiologi, dan gerakan sosial.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Cantrik Pustaka',
    slug: 'cantrik-pustaka',
    logo: 'publishers/cantrik.png',
    email: 'cantrikpustaka@gmail.com',
    phone: '0857-1234-5678',
    website: 'https://cantrikpustaka.com',
    address: 'Bantul, Yogyakarta',
    description: 'Penerbit sastra independen yang aktif menerbitkan kumpulan puisi, cerpen, dan novel alternatif.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Basabasi',
    slug: 'penerbit-basabasi',
    logo: 'publishers/basabasi.png',
    email: 'basabasistore@gmail.com',
    phone: '0813-1234-5678',
    website: 'https://basabasi.co',
    address: 'Yogyakarta',
    description: 'Imprint DIVA Press yang fokus menerbitkan novel fiksi berkualitas, novel klasik, dan esai.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Spring',
    slug: 'penerbit-spring',
    logo: 'publishers/spring.png',
    email: 'redaksi@penerbitspring.com',
    phone: '0354-68899',
    website: 'https://penerbitspring.com',
    address: 'Kediri, Jawa Timur',
    description: 'Imprint Penerbit Haru yang mempublikasikan novel romansa Barat (YA/NA) populer.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'PlotPoint Publishing',
    slug: 'plotpoint',
    logo: 'publishers/plotpoint.png',
    email: 'info@plotpointcreative.com',
    phone: '021-7199988',
    website: null,
    address: 'Jakarta',
    description: 'Penerbit kreatif berfokus pada penceritaan fiksi visual, skenario, dan novel remaja.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Stiletto Book',
    slug: 'stiletto-book',
    logo: 'publishers/stiletto.png',
    email: 'stilettobook@yahoo.com',
    phone: '0274-453300',
    website: 'https://stilettobook.com',
    address: 'Yogyakarta',
    description: 'Penerbit spesialis novel chic-lit, fiksi wanita (women’s fiction), dan parenting.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Renata Media / Akad',
    slug: 'penerbit-akad',
    logo: 'publishers/akad.png',
    email: 'redaksi.akad@gmail.com',
    phone: '0812-9900-1122',
    website: 'https://penerbitakad.com',
    address: 'Depok, Jawa Barat',
    description: 'Penerbit novel Hype terdepan dari Wattpad dan AU (Alternate Universe) Twitter / TikTok.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Tekad Media / Penerbit Tekad',
    slug: 'penerbit-tekad',
    logo: 'publishers/tekad.png',
    email: 'redaksi.tekad@gmail.com',
    phone: '0812-8877-6655',
    website: null,
    address: 'Depok, Jawa Barat',
    description: 'Penerbit fiksi romansa remaja dan dewasa muda yang sangat populer di kalangan Gen Z.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Bumi Aksara',
    slug: 'bumi-aksara',
    logo: 'publishers/bumiaksara.png',
    email: 'info@bumiaksara.com',
    phone: '021-87798700',
    website: 'https://bumiaksara.com',
    address: 'Jakarta Timur',
    description: 'Penerbit buku pendidikan, hukum, perguruan tinggi, dan literatur umum.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Kencana / Prenada Media',
    slug: 'prenada-kencana',
    logo: 'publishers/prenada.png',
    email: 'pmg@prenadamedia.com',
    phone: '021-87783800',
    website: 'https://prenadamedia.com',
    address: 'Jakarta Timur',
    description: 'Penerbit terkemuka untuk akademisi, buku hukum, ekonomi, dan ilmu sosial.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Renebook',
    slug: 'renebook',
    logo: 'publishers/renebook.png',
    email: 'redaksi@renebook.com',
    phone: '021-78885566',
    website: 'https://renebook.com',
    address: 'Jakarta Selatan',
    description: 'Penerbit spesialis Islam populer, pemikiran filosofis ramah pemula, dan self-help.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit POP',
    slug: 'penerbit-pop',
    logo: 'publishers/pop.png',
    email: 'redaksi@penerbitpop.id',
    phone: '021-53650110',
    website: null,
    address: 'Jakarta Pusat',
    description: 'Imprint KPG yang khusus menerbitkan novel fiksi populer dan pop-culture.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Alexander Books',
    slug: 'alexander-books',
    logo: 'publishers/alexander.png',
    email: 'alexanderbooks@gmail.com',
    phone: null,
    website: null,
    address: 'Yogyakarta',
    description: 'Penerbit fiksi klasik terjemahan dan buku non-fiksi bersejarah.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Kompas Book Publishing',
    slug: 'buku-kompas',
    logo: 'publishers/bukukompas.png',
    email: 'buku@kompas.id',
    phone: '021-5347710',
    website: 'https://gerai.kompas.id',
    address: 'Palmerah Selatan, Jakarta Pusat',
    description: 'Penerbit buku jurnalisme bermutu, biografi politik, sejarah, dan dokumenter.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'UI Publishing (UI Press)',
    slug: 'ui-publishing',
    logo: 'publishers/uipress.png',
    email: 'uipress@ui.ac.id',
    phone: '021-7863470',
    website: 'https://uipublishing.ui.ac.id',
    address: 'Kampus UI Depok, Jawa Barat',
    description: 'Penerbitan resmi Universitas Indonesia untuk monograf ilmiah dan riset.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'UGM Press',
    slug: 'ugm-press',
    logo: 'publishers/ugmpress.png',
    email: 'ugmpress@ugm.ac.id',
    phone: '0274-561036',
    website: 'https://ugmpress.ugm.ac.id',
    address: 'Sleman, Yogyakarta',
    description: 'Penerbit akademis Universitas Gadjah Mada dengan fokus literatur ilmiah nasional.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'ITB Press',
    slug: 'itb-press',
    logo: 'publishers/itbpress.png',
    email: 'info@itbpress.id',
    phone: '022-2504257',
    website: 'https://itbpress.id',
    address: 'Bandung, Jawa Barat',
    description: 'Spesialis buku sains, teknologi, rekayasa, dan desain arsitektur.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Cendana Art Media',
    slug: 'cendana-art-media',
    logo: 'publishers/cendana.png',
    email: 'cendanaartmedia@gmail.com',
    phone: null,
    website: null,
    address: 'Yogyakarta',
    description: 'Penerbit independen untuk buku-buku seni rupa, desain, dan kebudayaan.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Jaringan Kerja Sastra (JKS)',
    slug: 'jks-publishing',
    logo: 'publishers/jks.png',
    email: 'jksastra@gmail.com',
    phone: null,
    website: null,
    address: 'Indonesia',
    description: 'Penerbit perorangan/komunitas untuk pengarsipan karya-karya penyair lokal.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Laksana',
    slug: 'penerbit-laksana',
    logo: 'publishers/laksana.png',
    email: 'redaksilaksana@gmail.com',
    phone: '0274-4332277',
    website: null,
    address: 'Yogyakarta',
    description: 'Imprint DIVA Press yang mempublikasikan buku Self-Help dan populer terkini.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Bupala',
    slug: 'penerbit-bupala',
    logo: 'publishers/bupala.png',
    email: 'bupalapublisher@gmail.com',
    phone: null,
    website: null,
    address: 'Bandung, Jawa Barat',
    description: 'Penerbit independen berspesialisasi novel sejarah fiksi dan budaya lokal.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Romancious',
    slug: 'penerbit-romancious',
    logo: 'publishers/romancious.png',
    email: 'romancious.redaksi@gmail.com',
    phone: '021-8770011',
    website: null,
    address: 'Jakarta',
    description: 'Lini fiksi dari Loveable yang fokus penuh pada cerpen Wattpad romantis remaja.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Bintang Media',
    slug: 'bintang-media',
    logo: 'publishers/bintangmedia.png',
    email: 'redaksi.bintangmedia@gmail.com',
    phone: '021-77881122',
    website: null,
    address: 'Depok, Jawa Barat',
    description: 'Penerbit novel remaja pop yang aktif mengadaptasi karya-karya penulis digital.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Pastel Books',
    slug: 'pastel-books',
    logo: 'publishers/pastelbooks.png',
    email: 'redaksi@mizan.com',
    phone: '022-7834154',
    website: 'https://mizanpublishing.com',
    address: 'Bandung, Jawa Barat',
    description: 'Lini Mizan khusus fiksi remaja (Young Adult) dan novel teenlit Hype.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Vice Versa',
    slug: 'vice-versa',
    logo: 'publishers/viceversa.png',
    email: 'viceversa.pub@gmail.com',
    phone: null,
    website: null,
    address: 'Surabaya, Jawa Timur',
    description: 'Penerbit indie spesialis fiksi ilmiah (Sci-Fi) dan fantasi lokal.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Aksara Maya',
    slug: 'aksara-maya',
    logo: 'publishers/aksaramaya.png',
    email: 'support@aksaramaya.com',
    phone: '021-7918800',
    website: 'https://aksaramaya.id',
    address: 'Jakarta Selatan',
    description: 'Penerbitan berbasis teknologi dan penyedia ekosistem buku digital.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Indie Book Corner',
    slug: 'indie-book-corner',
    logo: 'publishers/ibc.png',
    email: 'indiebookcorner@gmail.com',
    phone: '0817-460-507',
    website: 'https://indiebookcorner.com',
    address: 'Yogyakarta',
    description: 'Pionir penyedia jasa penerbitan mandiri (self-publishing) terpercaya di Indonesia.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Nulisbuku',
    slug: 'nulisbuku',
    logo: 'publishers/nulisbuku.png',
    email: 'admin@nulisbuku.com',
    phone: null,
    website: 'https://nulisbuku.com',
    address: 'Jakarta',
    description: 'Platform self-publishing print-on-demand mandiri pertama di Indonesia.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Guepedia',
    slug: 'guepedia',
    logo: 'publishers/guepedia.png',
    email: 'guepedia@gmail.com',
    phone: '0812-8765-4321',
    website: 'https://guepedia.com',
    address: 'Bogor, Jawa Barat',
    description: 'Platform penerbitan on-demand mandiri (self-publishing) bagi penulis pemula.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Bukrad',
    slug: 'penerbit-bukrad',
    logo: 'publishers/bukrad.png',
    email: 'redaksi@bukrad.com',
    phone: null,
    website: null,
    address: 'Malang, Jawa Timur',
    description: 'Penerbit komik lokal, zine, dan karya fiksi visual indie.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Metamorfosa',
    slug: 'metamorfosa-press',
    logo: 'publishers/metamorfosa.png',
    email: 'metamorfosa@gmail.com',
    phone: null,
    website: null,
    address: 'Surakarta, Jawa Tengah',
    description: 'Penerbit cetak terbatas untuk karya sastra indie dan antologi puisi.',
    is_official: false,
    status: 'active',
  },
  {
    name: 'Penerbit Kawan Pustaka',
    slug: 'kawan-pustaka',
    logo: 'publishers/kawanpustaka.png',
    email: 'redaksi@kawanpustaka.com',
    phone: '021-78883030',
    website: 'https://kawanpustaka.com',
    address: 'Jakarta Selatan',
    description: 'Menerbitkan buku-buku praktis, resep masakan, keahlian, dan buku pelajaran.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Agromedia Pustaka',
    slug: 'agromedia-pustaka',
    logo: 'publishers/agromedia.png',
    email: 'redaksi@agromedia.net',
    phone: '021-78883030',
    website: 'https://agromedia.net',
    address: 'Jakarta Selatan',
    description: 'Penerbit spesialis buku pertanian, perikanan, agrobisnis, dan hobi.',
    is_official: true,
    status: 'active',
  },
  {
    name: 'Penerbit Medress / Medpress',
    slug: 'media-pressindo',
    logo: 'publishers/medpress.png',
    email: 'medpressgroup@yahoo.com',
    phone: '0274-885239',
    website: null,
    address: 'Yogyakarta',
    description: 'Penerbit buku populer, sejarah nasional, kamus, dan fiksi hiburan.',
    is_official: true,
    status: 'active',
  },
];


// ----------------------------------------------------
// 🐬 LOGIC SEEDING FOR MYSQL
// ----------------------------------------------------
export async function seedMySQL(connection) {
  let firstPublisherId = null;

  for (const pub of publishersData) {
    const [result] = await connection.query(
      `INSERT INTO publishers 
       (name, slug, logo, email, phone, website, address, description, is_official, status) 
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
       ON DUPLICATE KEY UPDATE 
          name = VALUES(name), 
          logo = VALUES(logo),
          email = VALUES(email),
          phone = VALUES(phone),
          website = VALUES(website),
          address = VALUES(address),
          description = VALUES(description),
          is_official = VALUES(is_official),
          status = VALUES(status)`,
      [
        pub.name,
        pub.slug,
        pub.logo,
        pub.email,
        pub.phone,
        pub.website,
        pub.address,
        pub.description,
        pub.is_official,
        pub.status,
      ]
    );

    if (!firstPublisherId) firstPublisherId = result.insertId;
  }

  console.log('  └─ 🐬 [MySQL] PublisherSeeder executed.');
  return { firstPublisherId };
}

// ----------------------------------------------------
// ⚡ LOGIC SEEDING FOR POSTGRESQL / SUPABASE
// ----------------------------------------------------
export async function seedPostgres(client) {
  let firstPublisherId = null;

  for (const pub of publishersData) {
    const query = `
      INSERT INTO publishers 
      (name, slug, logo, email, phone, website, address, description, is_official, status) 
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) 
      ON CONFLICT (slug) DO UPDATE SET 
        name = EXCLUDED.name, 
        logo = EXCLUDED.logo, 
        email = EXCLUDED.email, 
        phone = EXCLUDED.phone, 
        website = EXCLUDED.website, 
        address = EXCLUDED.address, 
        description = EXCLUDED.description, 
        is_official = EXCLUDED.is_official, 
        status = EXCLUDED.status
      RETURNING id;
    `;

    const res = await client.query(query, [
      pub.name,
      pub.slug,
      pub.logo,
      pub.email,
      pub.phone,
      pub.website,
      pub.address,
      pub.description,
      pub.is_official,
      pub.status,
    ]);

    if (!firstPublisherId) firstPublisherId = res.rows[0].id;
  }

  console.log('  └─ ⚡ [Postgres] PublisherSeeder executed.');
  return { firstPublisherId };
}
