import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Mendapatkan path directory saat ini (ES Modules)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 1. Ambil nama migrasi dari argumen terminal
const migrationNameInput = process.argv[2];

if (!migrationNameInput) {
  console.error('\x1b[31m%s\x1b[0m', '❌ Error: Harap masukkan nama migrasi!');
  console.log('Contoh: npm run make:migration create_books_table\n');
  process.exit(1);
}

// Format nama migrasi (mengubah spasi/dash menjadi underscore)
const cleanName = migrationNameInput.toLowerCase().replace(/[\s-]+/g, '_');

// 2. Tentukan target folder database/migrations/
const targetDir = path.resolve(__dirname, '../../database/migrations');

// Pastikan folder database/migrations/ sudah ada
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

// 🔒 FITUR KEAMANAN: Cek apakah nama migrasi sudah ada sebelumnya (walaupun timestamp beda)
const existingFiles = fs.readdirSync(targetDir);
const isDuplicate = existingFiles.some((file) => {
  // Mencocokkan bagian nama setelah timestamp (misal: 20260809112734_create_books_table.sql -> create_books_table.sql)
  const fileWithoutTimestamp = file.replace(/^\d{14}_/, '');
  return fileWithoutTimestamp === `${cleanName}.sql`;
});

if (isDuplicate) {
  console.error(
    '\x1b[31m%s\x1b[0m',
    `🚫 Cancelled: Migrasi dengan nama '${cleanName}' sudah ada di folder database/migrations/!`
  );
  console.log('Gunakan nama migrasi yang berbeda atau hapus file migrasi lama terlebih dahulu.\n');
  process.exit(1);
}

// 3. Format nama file baru: YYYYMMDDHHMMSS_nama_migrasi.sql
const now = new Date();
const timestamp = [
  now.getFullYear(),
  String(now.getMonth() + 1).padStart(2, '0'),
  String(now.getDate()).padStart(2, '0'),
  String(now.getHours()).padStart(2, '0'),
  String(now.getMinutes()).padStart(2, '0'),
  String(now.getSeconds()).padStart(2, '0'),
].join('');

const fileName = `${timestamp}_${cleanName}.sql`;
const filePath = path.join(targetDir, fileName);

// 4. Boilerplate / Template SQL
const sqlTemplate = `-- Migration: ${cleanName}
-- Created at: ${now.toISOString()}

-- Write your UP migration SQL here
-- Example:
-- CREATE TABLE example (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     created_at TIMESTAMPTZ DEFAULT NOW()
-- );
`;

// 5. Tulis file
try {
  fs.writeFileSync(filePath, sqlTemplate, 'utf8');
  console.log('\x1b[32m%s\x1b[0m', `✅ Migration created successfully!`);
  console.log(`📄 Path: database/migrations/${fileName}`);
} catch (error) {
  console.error('\x1b[31m%s\x1b[0m', '❌ Gagal membuat file migrasi:', error.message);
}
